### ISSUE TITLE
the favicon is hard to see

### ISSUE THREAD

**Issue by pbellec** [neurolibre/docs.neurolibre.com#1]
Would need to be cropped.
It is located here https://github.com/neurolibre/docs.neurolibre.com/blob/master/source/img/logo_neurolibre_small.png

**Comment by agahkarakuzu** [comment]
I guess you just want to keep the neuron body for the favicon? 

Something like this:

![image](https://user-images.githubusercontent.com/9632322/76978963-b88d9800-690d-11ea-8146-f9299535e45a.png)

I can resize it as you like.

**Comment by pbellec** [comment]
looks as good as a one-eyed chicken with a weird leg will ever do.

**Comment by agahkarakuzu** [comment]
I would not be surprised seeing a conp favicon pecking my window. I would even feed it some quinoa, if it were not for the self isolation. 

👀 should I just resize the original logo?

**Comment by agahkarakuzu** [comment]
https://github.com/neurolibre/neurolibre.com/issues/4#issuecomment-604159331

**Comment by pbellec** [comment]
the new favicon is very nice! will import it here.

**Comment by pbellec** [comment]
actually I am going to wait for the style of the docs to be settled.

**Comment by agahkarakuzu** [comment]
f71c11e9c8a0428bab59088e60e08b1063e64e00
