### ISSUE TITLE
color palette of the logo

### ISSUE THREAD

**Issue by pbellec** [neurolibre/docs.neurolibre.com#3]
The red logo does not work with the readthedocs theme.

For the main website, we should stick to the CONP red.

But for the docs, I think it would make sense to have a different palette.
Have the book in white, get rid of the current white outline, and turn the neuron into black would be sober and nice, I think. 

The corresponding file is located here: 
https://github.com/neurolibre/docs.neurolibre.com/blob/master/source/img/logo_neurolibre.png

**Comment by agahkarakuzu** [comment]
👍 I'll do this quickly.

**Comment by agahkarakuzu** [comment]
I guess this is close to what you want:

![logo_neurolibre_v2](https://user-images.githubusercontent.com/9632322/76977581-e1149280-690b-11ea-8481-22c511540013.png)

**Comment by ltetrel** [comment]
we don't see properly the logo on this page https://docs.neurolibre.com/en/latest/index.html

**Comment by ltetrel** [comment]
It was working before with red, why are we changing it I don't get it ?

**Comment by emdupre** [comment]
If we're updating the site theme in #4, we don't necessarily need to stick to a RTD-style (blue, grey, and white) theme, so the logo could stay red. 

It'd be great to have an SVG, though, rather than a PNG, so we could iterate faster on colors  ! Is one already available ?

**Comment by agahkarakuzu** [comment]
@emdupre I can sketch one tomorrow 🤞🏻

**Comment by agahkarakuzu** [comment]
SVG logo is also done: 

https://github.com/neurolibre/neurolibre.com/issues/4#issuecomment-604159331

**Comment by agahkarakuzu** [comment]
SVG files are available at: 

https://github.com/neurolibre/neurolibre.com/tree/master/static/img
