### ISSUE TITLE
Opinion on the new theme

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/docs.neurolibre.com#6]
Here is my point of view with the new theme. 

These could be some points for discussion :
* The colors for the notes and warnings are quite harsh, I think we should add some transparency. And also add a distinction between the title and content (the old warnings and note are just really great).
* The layout of the doc is not clear. I don't understand how do I navigate from the different pages with the top border. And most of them are dead links so not usefull.
* I think the overall fonts are too small.
* For some sub items, the fonts are larger than the top items (ex https://docs.neurolibre.com/en/latest/INFRASTRUCTURE.html#appendix-a)

Personally I am a real fan of the old new style, but let be open to discussion ;P

What do you think everyone ?

**Comment by pbellec** [comment]
I agree with your concerns Loic. Currently readibility and layout are problematic. It would require major tweaking with the theme. The color palette can be made more "neurolibresque", but the colors are indeed quite harsh for notes, warnings etc. At this stage I would also be in favour to go back to the previous theme. Also, I don't think it is a big deal to have different color palettes for the docs and the main website.

**Comment by emdupre** [comment]
Up to y'all, of course, how you want to handle it. All of the current concerns can be quickly addressed in the conf.py and in some light CSS, but I was trying to have something a bit slicker than the default RTD theme if we'd like to have it clickable from some of the Hugo themes without a significant thematic shit. 

I don't think this is my part of the project, though, so I was just offering one option.

**Comment by ltetrel** [comment]
If we want to have a less thematic shift, maybe we could just change the color palette (from RTD theme) as pierre pointed out ? what do you think @emdupre ? For example with a white background instead of the blue we could keep the original red neurolibre logo

**Comment by emdupre** [comment]
I don't think just a color change will avoid the thematic shift (although it will be an important part, once the skeleton is finalized). I was looking at e.g. ObservableHQ, which @agahkarakuzu had suggested as one possible inspiration source for NeuroLibre: https://observablehq.com/explore

Their navigation is along the top, much as in the Sphinx-Bootstrap theme -- honestly, it's likely based on Bootstrap itself. If you stick with the RTD theme, you'll switch from a top navbar to a side one, which is a shift no matter the color scheme :smile_cat: 

Again, though, this isn't really my arena, so only offering options.

**Comment by pbellec** [comment]
I have never tweaked a sphinx theme, so not sure how much work this will be. I agree with Loic that the RTD theme looks more polished out of the box, but let's see if we can get this sorted. It would be neat to have a consistent style for the docs and the main site. @agahkarakuzu @mathieuboudreau let me know if you would have time / be interested in looking into this. Otherwise I'll try.

**Comment by pbellec** [comment]
OK so I have slept on this. I don't think it's a good idea to match the style of the docs to the main website. The docs aimed at authors/reviewers should be integrated directly in neurolibre.com. Hugo is perfectly apt to do that, and it will be less confusing than being bounced around. The technical documentation is aimed at developers, and should have its own identity. The content would be limited to https://docs.neurolibre.com/en/latest/INFRASTRUCTURE.html, which would be split into different sections. @ltetrel what do you think

**Comment by ltetrel** [comment]
> OK so I have slept on this. I don't think it's a good idea to match the style of the docs to the main website. The docs aimed at authors/reviewers should be integrated directly in neurolibre.com. Hugo is perfectly apt to do that, and it will be less confusing than being bounced around different sites. The technical documentation is aimed at developers, and should have its own identity. The content would be limited to https://docs.neurolibre.com/en/latest/INFRASTRUCTURE.html, which would be split into different sections.

I was exactly thinking the same!

**Comment by pbellec** [comment]
Based on internal poll, we'll switch back to RTD theme for now. Exact content for docs still in discussion.
